name: apk
description: "A new Flutter project."
publish_to: 'none' # This prevents the package from being published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_spinkit: ^5.2.1 # Check for updates
  flutter_svg: ^2.0.10+1 # or the latest version
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_core: ^3.4.0
  geolocator: ^12.0.0
  geolocator_android: 4.6.1
  connectivity_plus: ^6.1.0 # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"  # Path to your main app icon
  adaptive_icon_background: "#00A000"  # Green background color for adaptive icons
  adaptive_icon_foreground: "assets/playstore.png"  # Path to the adaptive foreground image
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
